### ISSUE TITLE
does the system support transmission of point cloud online?like tcp?

### ISSUE THREAD

**Issue by xuyiqun** [cwi-dis/cwi-pcl-codec#12]

**Comment by jackjansen** [comment]
This repository does not but https://github.com/cwi-dis/cwipc does.

The codec in there is essentially the same codec as this one, but repackaged. Eventually that repo will replace this one, but that may take a while longer.

the `cwipc` suite contains not only our codec but also capturers for Realsense and Kinect, offline capturing, transmission and APIs for C, C++, Python and C#.
