### ISSUE TITLE
Segmentation fault (core dumped) when coding a ply file

### ISSUE THREAD

**Issue by jasmine19920** [cwi-dis/cwi-pcl-codec#7]
I compiled 'evaluate_compression' successfully on Ubuntu 16.04 with PCL-1.8.0.
When I try to test it, for example, with './evaluate_compression -h', the help information can be printed in the terminal, but end with a 'Segmentation fault (core dumped)' at the last line.
Then I attempt to encode a ply file 'Facade_00015_vox14' (one of mpeg-pcc test materials) as below:
`yangmei@min-100:~/MPEG-PCC/anchor/cwi-pcl-codec/build/apps/evaluate_compression$ ./evaluate_compression -i ./input -o ./output  --debug_level=3`

The print information in terminal is as following:

`Using '/home/yangmei/MPEG-PCC/anchor/cwi-pcl-codec/build/apps/evaluate_compression/parameter_config.txt'`  
`debug_level=3`
	 `K_outlier_filter=0`
	 `algorithm (default)=V2`
	 `bb_expand_factor=0.2`
	 `color_bits=8`
	 `color_coding_type=1`
	 `create_scalable (default)=0`
	 `debug_level=3`
	 `do_connectivity_coding (default)=0`
	 `do_delta_coding=1`
	 `do_icp_color_offset=0`
	 `do_quality_computation (default)=0`
	 `enh_bits=0`
	 `group_size (default)=0`
	 `icp_on_original=0`
`> input_directories[0]=./input`
	 `intra_frame_quality_csv=output/intra_frame_quality.csv`
	 `jpeg_quality=85`
	 `keep_centroid=0`
	 `macroblock_size=16`
	 `num_threads=1`
	 `octree_bits=14`
	 `octree_resolution (default)=0.2`
	 `output_directory=./output`
	 `point_resolution (default)=0.2`
	 `predictive_quality_csv=output/predictive_quality.csv`
	 `radius=0.1`
	` show_statistics (default)=0`
	 `visualization (default)=0`
`WITH_VTK='31'`
`re-intialized bounding box !!!`
 `octreeCoding 14820443 bytes  base layer`  
`Segmentation fault (core dumped)`

It seems a problem arising from writing the decoded ply file.
I deeply appreciate your help. Looking forward to your reply.

**Comment by keesblom** [comment]
Hi jasmine19920,

 I think both  Ubuntu 16.04 and PCL-1.8.0 are a bit outdated, we now use Ubuntu 18.04
and PCL 1.8.1/1.9.1; there I cannot reproduce your problems.
I don' have the dataset you mentioned (Facade_00015_vox14) and I cannot find it
anymore at the original MPEG repository.

Maybe it is a big dataset, when a very big data set is used on a machine with rather limited
memory, it is possible that the program crashes, since not all PCL modules
check the validity of newly allocated pointers.

You could try avoiding generating output files  by removing the line:
output_directory=./output
to check if your assumption is valid.

Regards,

Kees Blom.

**Comment by jasmine19920** [comment]
> Hi jasmine19920,
> 
> I think both Ubuntu 16.04 and PCL-1.8.0 are a bit outdated, we now use Ubuntu 18.04
> and PCL 1.8.1/1.9.1; there I cannot reproduce your problems.
> I don' have the dataset you mentioned (Facade_00015_vox14) and I cannot find it
> anymore at the original MPEG repository.
> 
> Maybe it is a big dataset, when a very big data set is used on a machine with rather limited
> memory, it is possible that the program crashes, since not all PCL modules
> check the validity of newly allocated pointers.
> 
> You could try avoiding generating output files by removing the line:
> output_directory=./output
> to check if your assumption is valid.
> 
> Regards,
> 
> Kees Blom.

Many thanks for your reply. I would try as your suggestion.
Currently, I use the order version codec, i.e.,  'pcl_mpeg_pcc_frame_coder' and 'pcc_mpeg_pcc_gop_coder', as suggested in CfP-V2 of MPEG PCC. They works quite well. 

Best regards,
Jasmine
