### ISSUE TITLE
the vector subscript out of range 

### ISSUE THREAD

**Issue by wjy8** [cwi-dis/cwi-pcl-codec#8]
I used Visual studio 2017 and PCL1.8.1 try to realize this project. But now I meet a problem:
Expression: vector  subscript out of range
For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.

I changed the value of the colorCodingType_arg variable to 1 and I want to use the snake mapping, which can be compiled. However, when running,there is a problem: the vector subscript out of range appears during the compilation process. All vectors define resize, but the same error still occurs.

I deeply appreciate your help. Looking forward to your reply.

**Comment by jackjansen** [comment]
Can you please provide the data needed to reproduce this problem? Or, if that is difficult (I can imagine the data is pretty large, with pointclouds): can you provide a stack trace? Building RelWithDebInfo should result in a usable stack trace, and the performance is much better than with Debug builds.

**Comment by keesblom** [comment]
Ik dacht dat de ‘snake mapping' een laat experiment van Rufael was
Ik vraag me af of het ooit goed is uit ontwikkeld.

**Comment by jackjansen** [comment]
@keesblom maybe we should use english:-)
If you think that snake mapping isn't fully implemented you're probably right, you know the code better than I do.

So, @wjy8: apparently this feature isn't enabled by default for nothing: it doesn't work. Sorry...

Of course, if you get it to work and are willing to share the fix we'll try to incorporate it.

**Comment by wjy8** [comment]
> @keesblom maybe we should use english:-)
> If you think that snake mapping isn't fully implemented you're probably right, you know the code better than I do.
> So, @wjy8: apparently this feature isn't enabled by default for nothing: it doesn't work. Sorry...
> Of course, if you get it to work and are willing to share the fix we'll try to incorporate it.
First, my data set is based on the website you provided : https://vcl.iti.gr/dataset/reconstruction/ 
Dimitris-PoissonHigh.rar.
Secondly, I try to use RelWithDebInfo , and problem is about vtk.

**Comment by keesblom** [comment]
'snake-mapping' refers to the zig-zag scanning pattern as defined in the JPEG standard
and is often optimal, so it should work and on MacOS 10.14.6 it does work properly with the
Dimitris-PoissonHigh dataset, therefore re-opening.
Still need to verify Visual studio 2017 and PCL1.8.1 (we now use PCL 1.9.1).

**Comment by wjy8** [comment]
> '蛇形映射'指的是JPEG标准中定义的之字形扫描模式，
> 并且通常是最佳的，因此它应该可以工作，并且在MacOS 10.14.6上它可以与
> Dimitris-PoissonHigh数据集一起正常工作，因此重新打开。
> 还需要验证Visual Studio 2017和PCL1.8.1（我们现在使用的是PCL 1.9.1）。

Thank you very much，I am planning to update my PCL library to version 1.9.0.
There are still a question. if I used jpeg
(change colorCodingType_arg = 1 and use std::vector<char>& pointDiffColorDataVector = jp_color_coder_.getDifferentialDataVector (); when decode differential color information)
 the compression ratio is increased by about four times, but the color attribute part loses too much information, so that the output is a black outline.

**Comment by wjy8** [comment]
> 'snake-mapping' refers to the zig-zag scanning pattern as defined in the JPEG standard
> and is often optimal, so it should work and on MacOS 10.14.6 it does work properly with the
> Dimitris-PoissonHigh dataset, therefore re-opening.
> Still need to verify Visual studio 2017 and PCL1.8.1 (we now use PCL 1.9.1).

Thank you very much，I am planning to update my PCL library to version 1.9.1.
There are still a question. if I used jpeg
(change colorCodingType_arg = 1 and use std::vector& pointDiffColorDataVector = jp_color_coder_.getDifferentialDataVector (); when decode differential color information)
the compression ratio is increased by about four times, but the color attribute part loses too much information, so that the output is a black outline.

**Comment by keesblom** [comment]
Expanded 'README.md' to point out that 'libjpeg-turbo-2.0.2' should be build and installed
using 'Visual Studio 2017' and the source code because of recent changes in Visual Studio 2017
(for 'libjpeg-turbo-2.0.2' the binary installer should not be used).
 
Tested with Visual studio 2017 and PCL1.9.1

**Comment by wjy8** [comment]
> 扩展'README.md'以指出'libjpeg-turbo-2.0.2'应该
> 使用'Visual Studio 2017'和源代码进行构建和安装，因为Visual Studio 2017最近发生了变化
> （对于'libjpeg-turbo-2.0' .2'不应使用二进制安装程序）。
> 
> 使用Visual Studio 2017和PCL1.9.1进行测试

hello keesblom，
Now I get the project "libjpeg-turbo.sln", but I can not find "libjpeg-turbo64/include" and "turbojpeg-static.lib", so I can not connection the "libjpeg-turbo.sln" and "CWI_PCL_CODEC.sln".
And I can not understand how to select the 'INSTALL' Project to build and install 'libjpeg-turbo-2.0.2', just one interface and one interface to connect?

**Comment by keesblom** [comment]
Hi wjy8,

you open  "libjpeg-turbo.slln”  in VisualStudio2019, and in “Solution Explorer” right-click “INSTALL” and select  “Project Only”->”Build..”.
This will build and install "libjpeg-turbo” in the directory “C:/libjpeg-turbo64”.
Next using CMake to configure “cwi-pcl-codec”  the necessary files will be found.
You can select alternative directoriy names in ‘CMakei’  (select ’Advanced’)

Regards,

Kees Blom.

**Comment by wjy8** [comment]
hello keesblom，
Now I get the files about "libjpeg-turbo64/include"(jconfig.h  jerror.h  jmorecfg.h   jpeglib.h  turbojpeg.h ) and "turbojpeg-static.lib". I change the JPEG_Turbo_INCLUDE_DIR (C:/libjpeg-turbo64/include)  and JPEG_Turbo_LIBRARY (C:/libjpeg-turbo64/lib/turbojpeg-static.lib) in cmake.
then I change the parameter jpeg_quality_arg=80 and colorCodingType_arg=1， run the project.  
For the Color bytes per points column,  the original 4bytes color attribute is compressed to only 0.017528 bytes, the color attribute compression rate is about: 228. As a result, the output is a black outline.

**Comment by wjy8** [comment]
hello keesblom,
Now I want to finish PCC（point cloud compression） with jpeg, can you tell me something about I need to change which part of the code

**Comment by wjy8** [comment]
> Hi wjy8, you open "libjpeg-turbo.slln” in VisualStudio2019, and in “Solution Explorer” right-click “INSTALL” and select “Project Only”->”Build..”. This will build and install "libjpeg-turbo” in the directory “C:/libjpeg-turbo64”. Next using CMake to configure “cwi-pcl-codec” the necessary files will be found. You can select alternative directoriy names in ‘CMakei’ (select ’Advanced’) Regards, Kees Blom.
> […](#)
> On 9 Sep 2019, at 09:07, wjy8 ***@***.***> wrote: 扩展'README.md'以指出'libjpeg-turbo-2.0.2'应该 使用'Visual Studio 2017'和源代码进行构建和安装，因为Visual Studio 2017最近发生了变化 （对于'libjpeg-turbo-2.0' .2'不应使用二进制安装程序）。 使用Visual Studio 2017和PCL1.9.1进行测试 hello keesblom， Now I get the project "libjpeg-turbo.sln", but I can not find "libjpeg-turbo64/include" and "turbojpeg-static.lib", so I can not connection the "libjpeg-turbo.sln" and "CWI_PCL_CODEC.sln". And I can not understand how to select the 'INSTALL' Project to build and install 'libjpeg-turbo-2.0.2', just one interface and one interface to connect? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

hello keesblom，
Now I get the files about "libjpeg-turbo64/include"(jconfig.h jerror.h jmorecfg.h jpeglib.h turbojpeg.h ) and "turbojpeg-static.lib". I change the JPEG_Turbo_INCLUDE_DIR (C:/libjpeg-turbo64/include) and JPEG_Turbo_LIBRARY (C:/libjpeg-turbo64/lib/turbojpeg-static.lib) in cmake.
then I change the parameter jpeg_quality_arg=80 and colorCodingType_arg=1， run the project.
For the Color bytes per points column, the original 4bytes color attribute is compressed to only 0.017528 bytes, the color attribute compression rate is about: 228. As a result, the output is a black outline.
Now I want to finish PCC（point cloud compression） with jpeg, can you tell me something about I need to change which part of the code

**Comment by keesblom** [comment]
Hello wjy8,

a quick response, since I’m not at the office today.

From your message I conclude that you can now build and run the project.

For the pointclouds that we worked with, the settings in the file ‘parameter_config.txt’
are known to work properly.
If you want to experiment with these settings, I would do this carefully: one-by-one, in small steps,
and record all effects.

IMHO libjpeg-turbo is preferred i.o. libjpeg because of its speed.
Possibly the compression code is compatible with libjpeg, but I never tried this exercise,
you’re on your own here.

Regards,

Kees Blom.

**Comment by wjy8** [comment]
> 嗨，wjy8，您在VisualStudio2019中打开“ libjpeg-turbo.slln”，然后在“解决方案资源管理器”中右键单击“安装”，然后选择“仅项目”->“构建..”。这将构建并安装“ libjpeg-turbo” ”在目录“ C：/ libjpeg-turbo64”中。接下来使用CMake配置“ cwi-pcl-codec”，将找到必要的文件。您可以在“ CMakei”（选择“高级”）方面（Kees Blom）选择其他目录名称。
> […](#)
> On 9 Sep 2019, at 09:07, wjy8 ***@***.***> wrote: 扩展'README.md'以指出'libjpeg-turbo-2.0.2'应该 使用'Visual Studio 2017'和源代码进行构建和安装，因为Visual Studio 2017最近发生了变化 （对于'libjpeg-turbo-2.0' .2'不应使用二进制安装程序）。 使用Visual Studio 2017和PCL1.9.1进行测试 hello keesblom， Now I get the project "libjpeg-turbo.sln", but I can not find "libjpeg-turbo64/include" and "turbojpeg-static.lib", so I can not connection the "libjpeg-turbo.sln" and "CWI_PCL_CODEC.sln". And I can not understand how to select the 'INSTALL' Project to build and install 'libjpeg-turbo-2.0.2', just one interface and one interface to connect? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

Hello  keesblom，I am sorry to bother you again. Now I still work on the libjpeg about point cloud and I want to do the quality assessment and PSNR of point cloud, and can you share your way of the assessment of point cloud, and I can know if the way is feasible.(I get the .ply file which is a 3D file) . My email adress is wujunyibupt@163.com.
I deeply appreciate your help. Looking forward to your reply.
